Grand.Web/Areas/Admin/Models/Stores/StoreModel.cs
using FluentValidation.Attributes;
using Grand.Framework.Localization;
using Grand.Framework.Mvc.ModelBinding;
using Grand.Framework.Mvc.Models;
using Grand.Web.Areas.Admin.Validators.Stores;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Grand.Web.Areas.Admin.Models.Stores
{
    [Validator(typeof(StoreValidator))]
    public partial class StoreModel : BaseGrandEntityModel, ILocalizedModel<StoreLocalizedModel>
    {
        public StoreModel()
        {
            Locales = new List<StoreLocalizedModel>();
            AvailableLanguages = new List<SelectListItem>();
            AvailableWarehouses = new List<SelectListItem>();
            AvailableCountries = new List<SelectListItem>();
        }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.Name")]
        
        public string Name { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.Url")]
        
        public string Url { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.SslEnabled")]
        public virtual bool SslEnabled { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.SecureUrl")]
        
        public virtual string SecureUrl { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.Hosts")]
        
        public string Hosts { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyName")]
        
        public string CompanyName { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyAddress")]
        
        public string CompanyAddress { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyPhoneNumber")]
        
        public string CompanyPhoneNumber { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyVat")]
        
        public string CompanyVat { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyEmail")]

        public string CompanyEmail { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyHours")]

        public string CompanyHours { get; set; }

        public IList<StoreLocalizedModel> Locales { get; set; }
        //default language
        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.DefaultLanguage")]
        
        public string DefaultLanguageId { get; set; }
        public IList<SelectListItem> AvailableLanguages { get; set; }

        //default warehouse
        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.DefaultWarehouse")]
        
        public string DefaultWarehouseId { get; set; }
        public IList<SelectListItem> AvailableWarehouses { get; set; }

        //default country
        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.DefaultCountry")]

        public string DefaultCountryId { get; set; }
        public IList<SelectListItem> AvailableCountries { get; set; }

    }

    public partial class StoreLocalizedModel : ILocalizedModelLocal
    {
        public string LanguageId { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.Name")]
        
        public string Name { get; set; }
    }
}

Grand.Web/Areas/Admin/Controllers/StoreController.cs
using Grand.Framework.Controllers;
using Grand.Framework.Kendoui;
using Grand.Framework.Mvc.Filters;
using Grand.Framework.Security.Authorization;
using Grand.Services.Localization;
using Grand.Services.Security;
using Grand.Services.Stores;
using Grand.Web.Areas.Admin.Extensions;
using Grand.Web.Areas.Admin.Models.Stores;
using Grand.Web.Areas.Admin.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Grand.Web.Areas.Admin.Controllers
{
    [PermissionAuthorize(PermissionSystemName.Stores)]
    public partial class StoreController : BaseAdminController
    {
        private readonly IStoreViewModelService _storeViewModelService;
        private readonly IStoreService _storeService;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;

        public StoreController(
            IStoreViewModelService storeViewModelService,
            IStoreService storeService,
            ILanguageService languageService,
            ILocalizationService localizationService)
        {
            this._storeViewModelService = storeViewModelService;
            this._storeService = storeService;
            this._languageService = languageService;
            this._localizationService = localizationService;
        }

        public IActionResult List() => View();

        [HttpPost]
        public async Task<IActionResult> List(DataSourceRequest command)
        {
            var storeModels = (await _storeService.GetAllStores())
                .Select(x => x.ToModel())
                .ToList();

            var gridModel = new DataSourceResult
            {
                Data = storeModels,
                Total = storeModels.Count()
            };

            return Json(gridModel);
        }

        public async Task<IActionResult> Create()
        {
            var model = _storeViewModelService.PrepareStoreModel();
            //locales
            await AddLocales(_languageService, model.Locales);
            //languages
            await _storeViewModelService.PrepareLanguagesModel(model);
            //warehouses
            await _storeViewModelService.PrepareWarehouseModel(model);
            //countries
            await _storeViewModelService.PrepareCountryModel(model);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public async Task<IActionResult> Create(StoreModel model, bool continueEditing)
        {
            if (ModelState.IsValid)
            {
                var store = await _storeViewModelService.InsertStoreModel(model);
                SuccessNotification(_localizationService.GetResource("Admin.Configuration.Stores.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = store.Id }) : RedirectToAction("List");
            }
            //languages
            await _storeViewModelService.PrepareLanguagesModel(model);
            //warehouses
            await _storeViewModelService.PrepareWarehouseModel(model);
            //countries
            await _storeViewModelService.PrepareCountryModel(model);

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var store = await _storeService.GetStoreById(id);
            if (store == null)
                //No store found with the specified id
                return RedirectToAction("List");

            var model = store.ToModel();
            //languages
            await _storeViewModelService.PrepareLanguagesModel(model);
            //warehouses
            await _storeViewModelService.PrepareWarehouseModel(model);
            //countries
            await _storeViewModelService.PrepareCountryModel(model);
            //locales
            await AddLocales(_languageService, model.Locales, (locale, languageId) =>
            {
                locale.Name = store.GetLocalized(x => x.Name, languageId, false, false);
            });
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public async Task<IActionResult> Edit(StoreModel model, bool continueEditing)
        {
            var store = await _storeService.GetStoreById(model.Id);
            if (store == null)
                //No store found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                store = await _storeViewModelService.UpdateStoreModel(store, model);
                SuccessNotification(_localizationService.GetResource("Admin.Configuration.Stores.Updated"));
                return continueEditing ? RedirectToAction("Edit", new { id = store.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            //languages
            await _storeViewModelService.PrepareLanguagesModel(model);
            //warehouses
            await _storeViewModelService.PrepareWarehouseModel(model);
            //countries
            await _storeViewModelService.PrepareCountryModel(model);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var store = await _storeService.GetStoreById(id);
            if (store == null)
                //No store found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                await _storeViewModelService.DeleteStore(store);
                SuccessNotification(_localizationService.GetResource("Admin.Configuration.Stores.Deleted"));
                return RedirectToAction("List");
            }
            ErrorNotification(ModelState);
            return RedirectToAction("Edit", new { id = store.Id });
        }
    }
}

Grand.Web/Areas/Api/Controllers/OData/StoreController.cs
using Grand.Api.Controllers;
using Grand.Api.Interfaces;
using Grand.Services.Security;
using Microsoft.AspNet.OData;
using Microsoft.AspNet.OData.Query;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Grand.Web.Areas.Api.Controllers.OData
{
    public partial class StoreController : BaseODataController
    {
        private readonly ICommonApiService _commonApiService;
        private readonly IPermissionService _permissionService;

        public StoreController(ICommonApiService commonApiService, IPermissionService permissionService)
        {
            _commonApiService = commonApiService;
            _permissionService = permissionService;
        }

        [HttpGet]
        public async Task<IActionResult> Get(string key)
        {
            if (!await _permissionService.Authorize(PermissionSystemName.Stores))
                return Forbid();

            var store = _commonApiService.GetStores().FirstOrDefault(x => x.Id == key);
            if (store == null)
                return NotFound();

            return Ok(store);
        }

        [HttpGet]
        [EnableQuery(HandleNullPropagation = HandleNullPropagationOption.False)]
        public async Task<IActionResult> Get()
        {
            if (!await _permissionService.Authorize(PermissionSystemName.Stores))
                return Forbid();

            return Ok(_commonApiService.GetStores());
        }
    }
}

Grand.Web/Areas/Admin/Views/Store/Create.cshtml
@model StoreModel
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Stores.AddNew").Text;
}
<form asp-controller="Store" asp-action="Create" method="post">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-shopping-cart"></i>
                        @T("Admin.Configuration.Stores.AddNew")
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Configuration.Stores.BackToList").Text, "List") </small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                            <vc:admin-widget widget-zone="store_details_buttons" additional-data="null" />
                        </div>
                    </div>
                </div>
                <div class="x_content form">
                   <partial name="_CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>

Grand.Web/Areas/Admin/Views/Store/Edit.cshtml
@model StoreModel
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Stores.EditStoreDetails").Text;
}
<form asp-controller="Store" asp-action="Edit" method="post">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-shopping-cart"></i>
                        @T("Admin.Configuration.Stores.EditStoreDetails") - @Model.Name
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Configuration.Stores.BackToList").Text, "List") </small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                            <span id="store-delete" class="btn red"><i class="fa fa-trash-o"></i> @T("Admin.Common.Delete")</span>
                            <vc:admin-widget widget-zone="store_details_buttons" additional-data="Model" />
                        </div>
                    </div>
                </div>
                <div class="x_content form">
                   <partial name="_CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>
<admin-delete-confirmation button-id="store-delete"/>

Grand.Web/Areas/Admin/Views/Store/List.cshtml
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Stores").Text;
}

<div class="row">
    <div class="col-md-12">
        <div class="x_panel light form-fit">
            <div class="x_title">
                <div class="caption">
                    <i class="fa fa-shopping-cart"></i>
                    @T("Admin.Configuration.Stores")
                </div>
                <div class="actions btn-group btn-group-devided">
                    <a href="@Url.Action("Create")" class="btn green"><i class="fa fa-plus"></i><span class="hidden-xs"> @T("Admin.Common.AddNew") </span></a>
                    <vc:admin-widget widget-zone="store_list_buttons" additional-data="null" />
                </div>
            </div>
            <div class="x_content form">
                <div class="form-horizontal">
                    <div class="form-body">
                        <div class="x_content">
                            <div id="stores-grid"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function () {
    $("#stores-grid").kendoGrid({
        dataSource: {
            transport: {
                read: {
                    url: "@Html.Raw(Url.Action("List", "Store"))",
                    type: "POST",
                    dataType: "json",
                    data: addAntiForgeryToken
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                errors: "Errors"
            },
            error: function(e) {
                display_kendoui_grid_error(e);
                // Cancel the changes
                this.cancelChanges();
            },
            serverPaging: true,
            serverFiltering: true,
            serverSorting: true
        },
        pageable: {
            refresh: true,
            numeric: false,
            previousNext: false,
            info: false
        },
        editable: {
            confirmation: false,
            mode: "inline"
        },
        scrollable: false,
        columns: [{
            field: "Name",
            title: "@T("Admin.Configuration.Stores.Fields.Name")",
            template: '<a class="k-link" href="Edit/#=Id#">#=kendo.htmlEncode(Name)#</a>',
        }, {
            field: "Url",
            title: "@T("Admin.Configuration.Stores.Fields.Url")"
        }, {
            field: "DisplayOrder",
            title: "@T("Admin.Configuration.Stores.Fields.DisplayOrder")"
        }]
    });
});
</script>

Grand.Web/Areas/Admin/Views/Store/_CreateOrUpdate.cshtml
@model StoreModel
<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<script type="text/javascript">
    $(document).ready(function () {

        $("#@Html.FieldIdFor(model => model.SslEnabled)").click(toggleSslEnabled);

        toggleSslEnabled();
    });

    function toggleSslEnabled() {
        if ($('#@Html.FieldIdFor(model => model.SslEnabled)').is(':checked')) {
            $('#pnlSecureUrl').show();
        }
        else {
            $('#pnlSecureUrl').hide();
        }
    }
</script>
<vc:admin-widget widget-zone="store_details_top" additional-data="Model" />
@(await Html.LocalizedEditor<StoreModel, StoreLocalizedModel>("store-localized",
    @<div class="form-horizontal">
         <div class="form-body">
             <div class="form-group">
                 <admin-label asp-for="@Model.Locales[item].Name" />
                 <div class="col-md-9 col-sm-9">
                     <admin-input asp-for="@Model.Locales[item].Name" />
                     <span asp-validation-for="@Model.Locales[item].Name"></span>
                 </div>
             </div>
             <input asp-for="@Model.Locales[item].LanguageId" type="hidden" />
         </div>
    </div>
    ,
    @<div class="form-horizontal">
         <div class="form-body">
             <div class="form-group">
                 <admin-label asp-for="Name" />
                 <div class="col-md-9 col-sm-9">
                     <admin-input asp-for="Name" />
                     <span asp-validation-for="Name"></span>
                 </div>
             </div>
         </div>
    </div>
))
<div class="form-horizontal">
    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="Url" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Url" />
                <span asp-validation-for="Url"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="SslEnabled" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                    <admin-input asp-for="SslEnabled" />
                    <div class="control__indicator"></div>
                </label>
                <span asp-validation-for="SslEnabled"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="note note-info">
                <em>@T("Admin.Configuration.Stores.Fields.SslEnabled.Hint2")</em>
            </div>
        </div>
        <div class="form-group" id="pnlSecureUrl">
            <admin-label asp-for="SecureUrl" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="SecureUrl" />
                <span asp-validation-for="SecureUrl"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Hosts" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Hosts" />
                <span asp-validation-for="Hosts"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="DefaultLanguageId" />
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="DefaultLanguageId" asp-items="Model.AvailableLanguages" />
                <span asp-validation-for="DefaultLanguageId"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="DisplayOrder" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="DisplayOrder" />
                <span asp-validation-for="DisplayOrder"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="CompanyName" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="CompanyName" />
                <span asp-validation-for="CompanyName"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="CompanyAddress" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="CompanyAddress" />
                <span asp-validation-for="CompanyAddress"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="CompanyPhoneNumber" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="CompanyPhoneNumber" />
                <span asp-validation-for="CompanyPhoneNumber"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="CompanyVat" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="CompanyVat" />
                <span asp-validation-for="CompanyVat"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="CompanyEmail" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="CompanyEmail" />
                <span asp-validation-for="CompanyEmail"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="CompanyHours" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="CompanyHours" />
                <span asp-validation-for="CompanyHours"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="DefaultWarehouseId" />
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="DefaultWarehouseId" asp-items="Model.AvailableWarehouses" />
                <span asp-validation-for="DefaultWarehouseId"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="DefaultCountryId" />
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="DefaultCountryId" asp-items="Model.AvailableCountries" />
                <span asp-validation-for="DefaultCountryId"></span>
            </div>
        </div>
    </div>
</div>
<vc:admin-widget widget-zone="store_details_bottom" additional-data="Model" />